<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="67" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="67" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
      <class name="com.testng.AnnotationDemo">
        <test-method status="PASS" signature="beoreSuite()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreSuite" is-config="true" duration-ms="9" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreSuite -->
        <test-method status="PASS" signature="beoreTest()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreTest" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreTest -->
        <test-method status="PASS" signature="beoreClass()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreClass" is-config="true" duration-ms="1" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreClass -->
        <test-method status="PASS" signature="beoreMethos()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreMethos" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreMethos -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="test1" duration-ms="4" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="beoreMethos()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreMethos" is-config="true" duration-ms="1" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreMethos -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterMethod" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="test2" duration-ms="2" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.testng.AnnotationDemo.test2(AnnotationDemo.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterMethod" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beoreMethos()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="beoreMethos" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreMethos -->
        <test-method status="SUCCESS_PERCENTAGE_FAILURE" signature="test4()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="test4" duration-ms="1" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.testng.AnnotationDemo.test4(AnnotationDemo.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterMethod" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="test3" duration-ms="0" started-at="2025-03-18T09:51:37 IST" depends-on-methods="com.testng.AnnotationDemo.test2" finished-at="2025-03-18T09:51:37 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AnnotationDemo.test3()[pri:0, instance:com.testng.AnnotationDemo@fe18270] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AnnotationDemo.test3()[pri:0, instance:com.testng.AnnotationDemo@fe18270] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterClass" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterTest" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.testng.AnnotationDemo@fe18270]" name="afterSuite" is-config="true" duration-ms="0" started-at="2025-03-18T09:51:37 IST" finished-at="2025-03-18T09:51:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.testng.AnnotationDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
