<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Asus-Vivobook-Mahesh" failures="2" tests="2" name="Default test(failed)" time="0.125" errors="0" timestamp="2024-07-08T08:21:36 IST">
  <testcase classname="com.exponent.AsserationTest" name="test2" time="0.034">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [10] but found [11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [10] but found [11]
at com.exponent.AsserationTest.test2(AsserationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.exponent.AsserationTest" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [10] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [11]
at com.exponent.AsserationTest.test1(AsserationTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
